repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: '^epistemix_platform/infrastructure/.*\.yml$'
      - id: check-added-large-files
      - id: check-json
        exclude: '^\.devcontainer/.*\.json$'
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black (commit - staged files only)
        language_version: python3.11
        exclude: ^fred-framework/
        stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black (push - all files)
        language_version: python3.11
        exclude: ^fred-framework/
        stages: [pre-push]
        pass_filenames: false
        args: [.]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "100"]
        exclude: ^fred-framework/

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--max-line-length=100", "--extend-ignore=E203,W503"]
        exclude: ^fred-framework/

  - repo: https://github.com/pycqa/pylint
    rev: v3.3.7
    hooks:
      - id: pylint
        args: ["--rcfile=.pylintrc", "--errors-only"]
        exclude: ^fred-framework/
        additional_dependencies:
          - pydantic
          - flask
          - flask-cors
          - sqlalchemy
          - boto3
          - click
          - returns
          - pandas
          - numpy
          - matplotlib
          - seaborn
          - python-dotenv
          - epx

  # CloudFormation linter for infrastructure files
  - repo: local
    hooks:
      - id: cfn-lint
        name: CloudFormation Linter
        entry: poetry run cfn-lint
        language: system
        files: '^epistemix_platform/infrastructure/.*\.yml$'
        pass_filenames: true

  # Pre-push hook for running tests
  - repo: local
    hooks:
      - id: pytest-epistemix-api
        name: Run epistemix_platform tests in parallel
        entry: poetry run pytest epistemix_platform/ -n auto
        language: system
        pass_filenames: false
        stages: [pre-push]
        always_run: true

exclude: ^fred-framework/
