template:
  type: file
  path: ecr/epistemix-api-repository.json

stack_name: epistemix-api-ecr

# No dependencies - ECR should be created first
dependencies: []

# Stack parameters
# Note: Environment is just for tagging - repository is shared across all environments
parameters:
  Environment: shared

# Stack-specific tags
tags:
  Owner: fred-simulations
  Component: ECR
  Service: EpistemixAPI
  Shared: "true"

# Sceptre hooks for template validation
validation_hooks: &validation_hooks
  - !cmd |
    echo '▶ (epistemix-api-ecr) Running cfn-lint...' && \
    cfn-lint templates/ecr/epistemix-api-repository.json && \
    echo '✓ (epistemix-api-ecr) cfn-lint passed'
  - !cmd |
    echo '▶ (epistemix-api-ecr) Running cfn-guard security validation...' && \
    cfn-guard validate \
      --data templates/ecr/epistemix-api-repository.json \
      --rules guard_rules/ecr_security_rules.guard \
      --show-summary fail && \
    echo '✓ (epistemix-api-ecr) cfn-guard passed'

hooks:
  before_validate: *validation_hooks
  before_create: *validation_hooks
  before_update: *validation_hooks
