template:
  type: file
  path: ecr/epistemix-api-repository.json

stack_name: epistemix-api-ecr

# No dependencies - ECR should be created first
dependencies: []

# Stack parameters
# Note: Environment is just for tagging - repository is shared across all environments
parameters:
  Environment: shared

# Stack-specific tags
tags:
  Owner: fred-simulations
  Component: ECR
  Service: EpistemixAPI
  Shared: "true"

# Sceptre hooks for template validation
hooks:
  before_create:
    - !cmd "cfn-lint templates/ecr/epistemix-api-repository.json"
    - !cmd "cfn-guard validate --data templates/ecr/epistemix-api-repository.json --rules guard_rules/ecr_security_rules.guard --show-summary fail"
  before_update:
    - !cmd "cfn-lint templates/ecr/epistemix-api-repository.json"
    - !cmd "cfn-guard validate --data templates/ecr/epistemix-api-repository.json --rules guard_rules/ecr_security_rules.guard --show-summary fail"
