template:
  type: file
  path: ecr/simulation-runner-repository.json

stack_name: fred-simulation-runner-ecr

# No dependencies - ECR should be created first
dependencies: []

# Stack parameters
# Note: Environment is just for tagging - repository is shared across all environments
parameters:
  RepositoryName: fred-simulation-runner
  Environment: shared
  EnableVulnerabilityScanning: "true"
  EnableCloudWatchLogs: "true"

# Stack-specific tags
tags:
  Owner: fred-simulations
  Component: ECR
  Service: SimulationRunner
  Shared: "true"

# Sceptre hooks for template validation
hooks:
  before_validate:
    - !cmd "echo '▶ Running cfn-lint on ECR template...' && cfn-lint templates/ecr/simulation-runner-repository.json && echo '✓ cfn-lint passed'"
    - !cmd "echo '▶ Running cfn-guard security validation...' && cfn-guard validate --data templates/ecr/simulation-runner-repository.json --rules guard_rules/ecr_security_rules.guard --show-summary fail && echo '✓ cfn-guard passed'"
  before_create:
    - !cmd "echo '▶ Running cfn-lint on ECR template...' && cfn-lint templates/ecr/simulation-runner-repository.json && echo '✓ cfn-lint passed'"
    - !cmd "echo '▶ Running cfn-guard security validation...' && cfn-guard validate --data templates/ecr/simulation-runner-repository.json --rules guard_rules/ecr_security_rules.guard --show-summary fail && echo '✓ cfn-guard passed'"
  before_update:
    - !cmd "echo '▶ Running cfn-lint on ECR template...' && cfn-lint templates/ecr/simulation-runner-repository.json && echo '✓ cfn-lint passed'"
    - !cmd "echo '▶ Running cfn-guard security validation...' && cfn-guard validate --data templates/ecr/simulation-runner-repository.json --rules guard_rules/ecr_security_rules.guard --show-summary fail && echo '✓ cfn-guard passed'"
