template:
  path: rds/rds-postgres.json

parameters:
  # Network Configuration
  # TODO: Update these values with actual staging VPC and subnet IDs
  VPCId: vpc-00bb33feebfb59191
  PrivateSubnetIds: subnet-0c6dc4a43d6d2269c,subnet-0065bf40913be1672
  VpcCidr: "172.31.0.0/16"

  # Database Configuration
  DBName: epistemixdb
  DBUsername: epistemixuser
  DBPassword: !environment_variable EPISTEMIX_DB_PASSWORD_STAGING
  DBInstanceClass: db.t3.small  # Slightly larger for staging
  AllocatedStorage: 50  # More storage for staging data

  # Security Settings
  PubliclyAccessible: "false"  # FRED-30: Database is NOT publicly accessible
  DeveloperIP: ""  # Set to your IP/32 for direct access if needed
  EnableVPCAccess: "true"  # Allows access from VPC CIDR block
  LambdaSecurityGroupId: ""  # TODO: Set staging Lambda security group ID

stack_tags:
  Project: epistemix-platform
  Environment: staging
  ManagedBy: sceptre

# Sceptre hooks for template validation
hooks:
  before_validate:
    - !cmd "echo '▶ Running cfn-lint on RDS template...' && cfn-lint templates/rds/rds-postgres.json && echo '✓ cfn-lint passed'"
    - !cmd "echo '▶ Running cfn-guard security validation...' && cfn-guard validate --data templates/rds/rds-postgres.json --rules guard_rules/rds_security_rules.guard --show-summary fail && echo '✓ cfn-guard passed'"
  before_create:
    - !cmd "echo '▶ Running cfn-lint on RDS template...' && cfn-lint templates/rds/rds-postgres.json && echo '✓ cfn-lint passed'"
    - !cmd "echo '▶ Running cfn-guard security validation...' && cfn-guard validate --data templates/rds/rds-postgres.json --rules guard_rules/rds_security_rules.guard --show-summary fail && echo '✓ cfn-guard passed'"
  before_update:
    - !cmd "echo '▶ Running cfn-lint on RDS template...' && cfn-lint templates/rds/rds-postgres.json && echo '✓ cfn-lint passed'"
    - !cmd "echo '▶ Running cfn-guard security validation...' && cfn-guard validate --data templates/rds/rds-postgres.json --rules guard_rules/rds_security_rules.guard --show-summary fail && echo '✓ cfn-guard passed'"
