template:
  type: file
  path: s3/s3-upload-bucket.json

# Stack parameters for staging environment
parameters:
  BucketName: fred-simulations-uploads-staging
  Environment: staging
  AllowedOrigins: "https://staging.fred-simulations.com,https://staging-api.fred-simulations.com"

# Stack-specific tags
tags:
  Environment: staging
  Owner: fred-simulations
  CostCenter: Staging
  Component: S3
  Service: FileUploads