template:
  type: file
  path: s3/s3-upload-bucket.json

stack_name: epistemix-uploads-staging-stack

# Stack parameters for staging environment
parameters:
  BucketName: epistemix-uploads-staging
  Environment: staging
  AllowedOrigins: "*"

# Stack-specific tags
tags:
  Owner: fred-simulations
  CostCenter: Staging
  Component: S3
  Service: FileUploads

# Sceptre hooks for template validation
hooks:
  before_validate:
    - !cmd "echo '▶ Running cfn-lint on S3 template...' && cfn-lint templates/s3/s3-upload-bucket.json && echo '✓ cfn-lint passed'"
    - !cmd "echo '▶ Running cfn-guard security validation...' && cfn-guard validate --data templates/s3/s3-upload-bucket.json --rules guard_rules/s3_security_rules.guard --show-summary fail && echo '✓ cfn-guard passed'"
  before_create:
    - !cmd "echo '▶ Running cfn-lint on S3 template...' && cfn-lint templates/s3/s3-upload-bucket.json && echo '✓ cfn-lint passed'"
    - !cmd "echo '▶ Running cfn-guard security validation...' && cfn-guard validate --data templates/s3/s3-upload-bucket.json --rules guard_rules/s3_security_rules.guard --show-summary fail && echo '✓ cfn-guard passed'"
  before_update:
    - !cmd "echo '▶ Running cfn-lint on S3 template...' && cfn-lint templates/s3/s3-upload-bucket.json && echo '✓ cfn-lint passed'"
    - !cmd "echo '▶ Running cfn-guard security validation...' && cfn-guard validate --data templates/s3/s3-upload-bucket.json --rules guard_rules/s3_security_rules.guard --show-summary fail && echo '✓ cfn-guard passed'"
