template:
  path: ec2/ssm-bastion.json

parameters:
  # Network Configuration
  VPCId: vpc-00bb33feebfb59191
  SubnetId: subnet-0c6dc4a43d6d2269c  # Use first private subnet

  # RDS Security Group (from staging RDS stack)
  # Uses CloudFormation export from the RDS stack
  RDSSecurityGroupId: !stack_output staging/rds-postgres.yaml::SecurityGroupId

  # Instance Configuration
  InstanceType: t3.nano  # Cost-optimized, can be stopped when not in use

stack_tags:
  Project: epistemix-platform
  Environment: staging
  ManagedBy: sceptre
  Purpose: SSM Bastion for RDS Access

# Sceptre hooks for template validation
validation_hooks: &validation_hooks
  - !cmd |
    echo '▶ (ssm-bastion) Running cfn-lint...' && \
    cfn-lint templates/ec2/ssm-bastion.json && \
    echo '✓ (ssm-bastion) cfn-lint passed'
  - !cmd |
    echo '▶ (ssm-bastion) Running cfn-guard security validation...' && \
    cfn-guard validate \
      --data templates/ec2/ssm-bastion.json \
      --rules guard_rules/ec2_security_rules.guard \
      --show-summary fail && \
    echo '✓ (ssm-bastion) cfn-guard passed'

hooks:
  before_validate: *validation_hooks
  before_create: *validation_hooks
  before_update: *validation_hooks
