# BUILD file for epistemix_platform mappers

python_sources(
    name="lib",
    sources=[
        "*.py",
    ],
    dependencies=[
        "epistemix_platform/models:lib",
        "epistemix_platform/repositories:lib",
        "//:root#sqlalchemy",
    ],
)