# BUILD file for epistemix_platform repositories

python_sources(
    name="lib",
    sources=[
        "*.py"
    ],
    dependencies=[
        "epistemix_platform/models:lib",
        "//:root#boto3",
        "//:root#botocore",
        "//:root#sqlalchemy",
    ]
)