python_test_utils(
    name="test-utils",
    resolve="infrastructure_env",
    dependencies=[
        "epistemix_platform/infrastructure:infrastructure-reqs#aws-cdk-lib",
        "epistemix_platform/infrastructure:infrastructure-reqs#pytest-snapshot",
    ],
)
